---
- name: OS Update Playbook
  hosts: all
  become: true
  remote_user: ansible

  tasks:
    - name: Upgrade all packages
      ansible.builtin.apt:
        upgrade: dist
        update_cache: true
        autoremove: true
      when: ansible_facts['os_family'] == 'Debian'

    - name: Reboot the system if required
      reboot:
        msg: "Rebooting after OS update"
        pre_reboot_delay: 10
        post_reboot_delay: 30
      when: ansible_facts['os_family'] == 'Debian'
